---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  name: docker
platforms:
  - name: test-ansible-self-signed-certificates
    image: buluma/docker-ubuntu-systemd:jammy
    pre_build_image: true
provisioner:
  name: ansible
  config_options:
    defaults:
      verbosity: 0
      nocows: 1
      stdout_callback: yaml
      display_skipped_hosts: false
      display_ok_hosts: true
      display_failed_stderr: true
      show_custom_stats: true
      show_task_path_on_failure: true
      callback_format_pretty: true
      callback_result_format: yaml
verifier:
  name: ansible
