---
- name: Prepare
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - include_role:
        name: buluma.bootstrap

    - include_role:
        name: buluma.python_pip

    - name: Install dependencies
      apt:
        update_cache: true
        name:
          - rsync
        state: present
